services:
  chinnaswamy:
    build: .
    depends_on:
      - cassandra
    ports:
      - "8080:8080"
    environment:
      CHINNASWAMY_PORT: "8080"
    networks:
      - "chinnaswamy-devnet"
    volumes:
      - ./conf.yaml:/conf.yaml

  cassandra:
    image: cassandra:4.0
    ports:
      - "9042:9042"
      - "9160:9160"
      - "7002:7002"
      - "7001:7001"
      - "7199:7199"
    volumes:
      - cassandra-data:/var/lib/cassandra
      - ./dev-cassandra.yaml:/etc/cassandra/cassandra.yaml
    networks:
      - "chinnaswamy-devnet"

networks:
  chinnaswamy-devnet:
    driver: bridge

volumes:
  cassandra-data:
