services:
  chinnaswamy:
    depends_on:
      - cassandra-test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      CHINNASWAMY_PORT: "8080"
      CHINNASWAMY_DATABASEADDRESSES: "cassandra-test"
    networks:
      - "chinnaswamy-testnet"

  cassandra-test:
    build:
      context: .
      dockerfile: Dockerfile.cassandra-test
    ports:
      - "9042:9042"
      - "9160:9160"
      - "7002:7002"
      - "7001:7001"
      - "7199:7199"
    volumes:
      - cassandra-test-data:/var/lib/cassandra
      - ./dev-cassandra.yaml:/etc/cassandra/cassandra.yaml
    networks:
      - "chinnaswamy-testnet"

networks:
  chinnaswamy-testnet:
    driver: bridge

volumes:
  cassandra-test-data: